name: Publish ${package_name} to PyPI / GitHub

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to Pypi
    runs-on: ubuntu-latest

    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}